# vim: set ft=conf :
# macOS-specific settings

font-size = 15
# adjust-cell-height = 1

# This is currently only supported on macOS
font-thicken = true
font-thicken-strength = 0

macos-titlebar-proxy-icon = hidden
window-padding-x = 3
window-padding-y = 0, 6

# -----------------------------------------------------------------------------
# Keybindings
# -----------------------------------------------------------------------------

keybind = global:super+shift+space=toggle_quick_terminal

# WIP: scrollback workwaround
keybind = super+shift+h=write_scrollback_file:paste,plain
