#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Nelson R Monserrate"
email = "nrmonserrate@gmail.com"

[ui]
pager = ["less", "-FRX"]
diff-formatter="delta"

[merge-tools.delta]
diff-args=["--side-by-side", "$left", "$right", "--width=$width"]
diff-expected-exit-codes = [0, 1]

[templates]
git_push_bookmark = '"nm/" ++ change_id.short()'

