# Defaults: https://github.com/helix-editor/helix/blob/master/languages.toml

# Python
[[language]]
name = "python"
rulers = [88, 120]
language-servers = ["pyright", "ruff"]
auto-format = true
formatter = { command = "ruff", args = [
  "format",
  "--stdin-filename",
  "dummy.py",
  "-",
] }

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config.python.analysis]
diagnosticMode = "openFilesOnly"

[language-server.ruff]
command = "ruff"
args = ["server"]

# Bash/Shell
[[language]]
name = "bash"
language-servers = ["bash-language-server"]
auto-format = true
formatter = { command = "shfmt", args = ["-i", "4", "-ci", "-"] }
indent = { tab-width = 4, unit = "    " }

[language-server.bash-language-server]
command = "bash-language-server"
args = ["start"]

[language-server.bash-language-server.config]
bashIde.shellcheckPath = "shellcheck"

# JSON
[[language]]
name = "json"
language-servers = ["vscode-json-language-server"]
auto-format = true
formatter = { command = "prettier", args = [
  "--parser",
  "json",
  "--tab-width",
  "2",
] }
indent = { tab-width = 2, unit = "  " }

# JSONC (JSON with Comments)
[[language]]
name = "jsonc"
language-servers = ["vscode-json-language-server"]
auto-format = true
formatter = { command = "prettier", args = [
  "--parser",
  "json",
  "--tab-width",
  "2",
] }
indent = { tab-width = 2, unit = "  " }

[language-server.vscode-json-language-server]
command = "vscode-json-language-server"
args = ["--stdio"]

# YAML
[[language]]
name = "yaml"
language-servers = ["yaml-language-server", "ansible-language-server"]
auto-format = true
formatter = { command = "yamlfmt", args = ['-'] }
indent = { tab-width = 2, unit = "  " }

[language-server.yaml-language-server]
command = "yaml-language-server"
args = ["--stdio"]

[language-server.ansible-language-server]
command = "ansible-language-server"
args = ["--stdio"]

# TOML
[[language]]
name = "toml"
language-servers = ["taplo"]
auto-format = true
formatter = { command = "taplo", args = ["format", "-"] }
indent = { tab-width = 2, unit = "  " }

[language-server.taplo]
command = "taplo"
args = ["lsp", "stdio"]

# Jinja2 templates
[[language]]
name = "jinja"
language-servers = ["jinja-lsp"]
auto-format = false

[language-server.jinja-lsp]
command = "jinja-lsp"
args = []

# Markdown
[[language]]
name = "markdown"
language-servers = ["marksman"]
auto-format = true
rulers = [120]
formatter = { command = "prettier", args = [
  "--parser",
  "markdown",
  "--prose-wrap",
  "preserve",
] }

[language-server.marksman]
command = "marksman"
args = ["server"]

[[language]]
name = "ini"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "nix"
language-servers = ["nixd"]
auto-format = true
formatter = { command = "nixfmt" }
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "env"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "git-rebase"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "git-config"
indent = { tab-width = 2, unit = "  " }

# Docker
[[language]]
name = "dockerfile"
scope = "source.dockerfile"
injection-regex = "docker|dockerfile"
roots = ["Dockerfile", "Containerfile"]
file-types = [
  "Dockerfile",
  { glob = "Dockerfile" },
  { glob = "Dockerfile.*" },
  "dockerfile",
  { glob = "dockerfile" },
  { glob = "dockerfile.*" },
  "Containerfile",
  { glob = "Containerfile" },
  { glob = "Containerfile.*" },
  "containerfile",
  { glob = "containerfile" },
  { glob = "containerfile.*" },
]
comment-token = "#"
indent = { tab-width = 4, unit = "    " }
auto-format = true
formatter = { command = "dockerfmt", args = ["-n", "-i", "4"] }
language-servers = ["docker-language-server"]

[[grammar]]
name = "dockerfile"
source = { git = "https://github.com/camdencheek/tree-sitter-dockerfile", rev = "087daa20438a6cc01fa5e6fe6906d77c869d19fe" }

[[language]]
name = "docker-compose"
language-id = "dockercompose"
scope = "source.yaml.docker-compose"
roots = [
  "docker-compose.yaml",
  "docker-compose.yml",
  "compose.yaml",
  "compose.yml",
]
language-servers = ["docker-language-server"]
file-types = [
  { glob = "docker-compose.yaml" },
  { glob = "docker-compose.yml" },
  { glob = "compose.yaml" },
  { glob = "compose.yml" },
]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
grammar = "yaml"

[language-server.docker-language-server]
command = "docker-language-server"
args = ["start", "--stdio"]
